-- Table: nibrs_12mc_offenders_arrestees

-- DROP TABLE nibrs_12mc_offenders_arrestees;

CREATE TABLE nibrs_12mc_offenders_arrestees
(
  offender_record_type character varying,
  offender_state_no character varying,
  offender_state character varying,
  offender_ori character varying,
  offender_incident character varying,
  offender_incident_date character varying,
  offender_seqno double precision,
  offender_age double precision,
  offender_gender character varying,
  offender_race character varying,
  offender_number_offenses double precision,
  offender_internal_offender_id double precision NOT NULL,
  offender_offender_ori9 character varying,
  offender_county_no character varying,
  offender_offenses_incident character varying,
  offender_ori9 character varying,
  offender_ucr_offense character varying,
  offender_attempted character varying,
  offender_arson integer DEFAULT 0,
  offender_aggravated_assault integer DEFAULT 0,
  offender_simple_assault integer DEFAULT 0,
  offender_intimidation integer DEFAULT 0,
  offender_bribery integer DEFAULT 0,
  offender_burglary integer DEFAULT 0,
  offender_forgery integer DEFAULT 0,
  offender_vandalism integer DEFAULT 0,
  offender_drugs_narcotics integer DEFAULT 0,
  offender_drug_equipment integer DEFAULT 0,
  offender_embezzlement integer DEFAULT 0,
  offender_extortion integer DEFAULT 0,
  offender_false_pretenses integer DEFAULT 0,
  offender_credit_card integer DEFAULT 0,
  offender_impersonation integer DEFAULT 0,
  offender_welfare_fraud integer DEFAULT 0,
  offender_wire_fraud integer DEFAULT 0,
  offender_betting integer DEFAULT 0,
  offender_operating_gambling integer DEFAULT 0,
  offender_gambling_equipment integer DEFAULT 0,
  offender_sports_tampering integer DEFAULT 0,
  offender_murder integer DEFAULT 0,
  offender_negligent_manslaughter integer DEFAULT 0,
  offender_justifiable_homicide integer DEFAULT 0,
  offender_sex_trafficking integer DEFAULT 0,
  offender_labor_trafficking integer DEFAULT 0,
  offender_kidnapping integer DEFAULT 0,
  offender_pocket_picking integer DEFAULT 0,
  offender_purse_snatching integer DEFAULT 0,
  offender_shoplifting integer DEFAULT 0,
  offender_building_theft integer DEFAULT 0,
  offender_theft_from_machine integer DEFAULT 0,
  offender_theft_from_auto integer DEFAULT 0,
  offender_auto_parts_theft integer DEFAULT 0,
  offender_other_theft integer DEFAULT 0,
  offender_auto_theft integer DEFAULT 0,
  offender_pornography integer DEFAULT 0,
  offender_prostitution integer DEFAULT 0,
  offender_prostitution_promotion integer DEFAULT 0,
  offender_prostitution_purchase integer DEFAULT 0,
  offender_robbery integer DEFAULT 0,
  offender_forcible_rape integer DEFAULT 0,
  offender_forcible_sodomy integer DEFAULT 0,
  offender_rape_object integer DEFAULT 0,
  offender_forcible_fondling integer DEFAULT 0,
  offender_incest integer DEFAULT 0,
  offender_statutory_rape integer DEFAULT 0,
  offender_stolen_property integer DEFAULT 0,
  offender_weapon integer DEFAULT 0,
  offender_assault_general integer DEFAULT 0,
  offender_drugs_general integer DEFAULT 0,
  offender_fraud_general integer DEFAULT 0,
  offender_gambling_general integer DEFAULT 0,
  offender_homicide_general integer DEFAULT 0,
  offender_trafficking_general integer DEFAULT 0,
  offender_theft_general integer DEFAULT 0,
  offender_prostitution_general integer DEFAULT 0,
  offender_sex_offense_forcible integer DEFAULT 0,
  offender_sex_offense_nonforcible integer DEFAULT 0,
  arrest_type character varying,
  arrest_ucr_offense character varying,
  arrest_gender character varying,
  arrest_state_no character varying,
  arrest_seqno character varying,
  arrest_age double precision,
  arrest_multiple_arrests character varying,
  arrest_state character varying,
  arrest_record_type character varying,
  arrest_incident character varying,
  arrest_transaction_number character varying,
  arrest_disposition_u18 character varying,
  arrest_race character varying,
  arrest_ori character varying,
  arrest_resident_status character varying,
  arrest_number_records double precision,
  arrest_ethnicity character varying,
  arrest_incident_date character varying,
  arrest_date character varying,
  arrest_internal_offender_id double precision,
  arrest_ori9 character varying,
  arrest_county_no character varying,
  arrest_arson integer DEFAULT 0,
  arrest_aggravated_assault integer DEFAULT 0,
  arrest_simple_assault integer DEFAULT 0,
  arrest_intimidation integer DEFAULT 0,
  arrest_bribery integer DEFAULT 0,
  arrest_burglary integer DEFAULT 0,
  arrest_forgery integer DEFAULT 0,
  arrest_vandalism integer DEFAULT 0,
  arrest_drugs_narcotics integer DEFAULT 0,
  arrest_drug_equipment integer DEFAULT 0,
  arrest_embezzlement integer DEFAULT 0,
  arrest_extortion integer DEFAULT 0,
  arrest_false_pretenses integer DEFAULT 0,
  arrest_credit_card integer DEFAULT 0,
  arrest_impersonation integer DEFAULT 0,
  arrest_welfare_fraud integer DEFAULT 0,
  arrest_wire_fraud integer DEFAULT 0,
  arrest_betting integer DEFAULT 0,
  arrest_operating_gambling integer DEFAULT 0,
  arrest_gambling_equipment integer DEFAULT 0,
  arrest_sports_tampering integer DEFAULT 0,
  arrest_murder integer DEFAULT 0,
  arrest_negligent_manslaughter integer DEFAULT 0,
  arrest_justifiable_homicide integer DEFAULT 0,
  arrest_sex_trafficking integer DEFAULT 0,
  arrest_labor_trafficking integer DEFAULT 0,
  arrest_kidnapping integer DEFAULT 0,
  arrest_pocket_picking integer DEFAULT 0,
  arrest_purse_snatching integer DEFAULT 0,
  arrest_shoplifting integer DEFAULT 0,
  arrest_building_theft integer DEFAULT 0,
  arrest_theft_from_machine integer DEFAULT 0,
  arrest_theft_from_auto integer DEFAULT 0,
  arrest_auto_parts_theft integer DEFAULT 0,
  arrest_other_theft integer DEFAULT 0,
  arrest_auto_theft integer DEFAULT 0,
  arrest_pornography integer DEFAULT 0,
  arrest_prostitution integer DEFAULT 0,
  arrest_prostitution_promotion integer DEFAULT 0,
  arrest_prostitution_purchase integer DEFAULT 0,
  arrest_robbery integer DEFAULT 0,
  arrest_forcible_rape integer DEFAULT 0,
  arrest_forcible_sodomy integer DEFAULT 0,
  arrest_rape_object integer DEFAULT 0,
  arrest_forcible_fondling integer DEFAULT 0,
  arrest_incest integer DEFAULT 0,
  arrest_statutory_rape integer DEFAULT 0,
  arrest_stolen_property integer DEFAULT 0,
  arrest_weapon integer DEFAULT 0,
  arrest_assault_general integer DEFAULT 0,
  arrest_drugs_general integer DEFAULT 0,
  arrest_fraud_general integer DEFAULT 0,
  arrest_gambling_general integer DEFAULT 0,
  arrest_homicide_general integer DEFAULT 0,
  arrest_trafficking_general integer DEFAULT 0,
  arrest_theft_general integer DEFAULT 0,
  arrest_prostitution_general integer DEFAULT 0,
  arrest_sex_offense_forcible integer DEFAULT 0,
  arrest_sex_offense_nonforcible integer DEFAULT 0,
  arrest_bad_check integer DEFAULT 0,
  arrest_loitering integer DEFAULT 0,
  arrest_disorder integer DEFAULT 0,
  arrest_dui integer DEFAULT 0,
  arrest_drunk integer DEFAULT 0,
  arrest_family_nonv integer DEFAULT 0,
  arrest_liquor_law integer DEFAULT 0,
  arrest_peeping_tom integer DEFAULT 0,
  arrest_runaway integer DEFAULT 0,
  arrest_trespass integer DEFAULT 0,
  arrest_other_offense integer DEFAULT 0
)
WITH (
  OIDS=FALSE
);
ALTER TABLE nibrs_12mc_offenders_arrestees
  OWNER TO roesler;
