import sqlalchemy as sa

conn = sa.create_engine('postgresql://roesler:break_free15@mugshots.cwwgybrqdl5n.us-west-1.rds.amazonaws.com:5432/Mugshots', echo=False)
conn.connect()

metadata = sa.MetaData()

# ACS counties info, 2009-2013
acs_counties_13 = sa.Table('acs_counties_13', metadata,
    sa.Column('acs_county_no', sa.String(), primary_key = True),
    sa.Column('total_residents', sa.Float), sa.Column('w_residents', sa.Float),
    sa.Column('b_residents', sa.Float), sa.Column('i_residents', sa.Float),
    sa.Column('a_residents', sa.Float), sa.Column('h_residents', sa.Float),
    sa.Column('o_residents', sa.Float), sa.Column('m_residents', sa.Float),
    sa.Column('mi_residents', sa.Float), sa.Column('mno_residents', sa.Float),
    sa.Column('b_residents_percent', sa.Float), sa.Column('w_residents_percent', sa.Float),
    sa.Column('bw_residents_pdiff', sa.Float), sa.Column('bw_residents_ratio', sa.Float),
    sa.Column('nonw_residents_percent', sa.Float), sa.Column('nonw_residents_percent_sq', sa.Float),
    sa.Column('b_residents_percent_sq', sa.Float), sa.Column('w_residents_percent_sq', sa.Float),
    sa.Column('bw_residents_percent', sa.Float), sa.Column('prop_residents_wnotb', sa.Float),
    sa.Column('total_gender', sa.Float), sa.Column('male', sa.Float),
    sa.Column('total_15_19', sa.Float), sa.Column('male_15_19', sa.Float),
    sa.Column('total_20_24', sa.Float), sa.Column('male_20_24', sa.Float),
    sa.Column('percent_male', sa.Float), sa.Column('w_total', sa.Float),
    sa.Column('w_male', sa.Float), sa.Column('w_male_18_19', sa.Float),
    sa.Column('w_male_20_24', sa.Float), sa.Column('w_male_18_24', sa.Float),
    sa.Column('b_total', sa.Float),
    sa.Column('b_male', sa.Float), sa.Column('b_male_18_19', sa.Float),
    sa.Column('b_male_20_24', sa.Float), sa.Column('b_male_18_24', sa.Float),
    sa.Column('ai_total', sa.Float),
    sa.Column('ai_male', sa.Float), sa.Column('ai_male_18_19', sa.Float),
    sa.Column('ai_male_20_24', sa.Float), sa.Column('ai_male_18_24', sa.Float),
    sa.Column('a_total', sa.Float),
    sa.Column('a_male', sa.Float), sa.Column('a_male_18_19', sa.Float),
    sa.Column('a_male_20_24', sa.Float), sa.Column('a_male_18_24', sa.Float),
    sa.Column('hw_total', sa.Float),
    sa.Column('hw_male', sa.Float), sa.Column('hw_male_18_19', sa.Float),
    sa.Column('hw_male_20_24', sa.Float), sa.Column('hw_male_18_24', sa.Float),
    sa.Column('o_total', sa.Float),
    sa.Column('o_male', sa.Float), sa.Column('o_male_18_19', sa.Float),
    sa.Column('o_male_20_24', sa.Float), sa.Column('o_male_18_24', sa.Float),
    sa.Column('unemployed', sa.Float), sa.Column('inc_households', sa.Float),
    sa.Column('under10', sa.Float), sa.Column('under10_percent', sa.Float),
    sa.Column('inc_10to15', sa.Float), sa.Column('inc_10to15_percent', sa.Float),
    sa.Column('inc_15to25', sa.Float), sa.Column('inc_15to25_percent', sa.Float),
    sa.Column('inc_25to35', sa.Float), sa.Column('inc_25to35_percent', sa.Float),
    sa.Column('inc_35to50', sa.Float), sa.Column('inc_35to50_percent', sa.Float),
    sa.Column('inc_50to75', sa.Float), sa.Column('inc_50to75_percent', sa.Float),
    sa.Column('inc_75to100', sa.Float), sa.Column('inc_75to100_percent', sa.Float),
    sa.Column('inc_100to150', sa.Float), sa.Column('inc_100to150_percent', sa.Float),
    sa.Column('inc_150to200', sa.Float), sa.Column('inc_150to200_percent', sa.Float),
    sa.Column('inc_200more', sa.Float), sa.Column('inc_200more_percent', sa.Float),
    sa.Column('inc_median', sa.Float), sa.Column('inc_mean', sa.Float),
    sa.Column('b_inc_total', sa.Float), sa.Column('b_inc_under10', sa.Float),
    sa.Column('b_inc_10to15', sa.Float), sa.Column('b_inc_15to20', sa.Float),
    sa.Column('b_inc_20to25', sa.Float), sa.Column('b_inc_25to30', sa.Float),
    sa.Column('b_inc_30to35', sa.Float), sa.Column('b_inc_35to40', sa.Float),
    sa.Column('b_inc_40to45', sa.Float), sa.Column('b_inc_45to50', sa.Float),
    sa.Column('b_inc_50to60', sa.Float), sa.Column('b_inc_60to75', sa.Float),
    sa.Column('b_inc_75to100', sa.Float), sa.Column('b_inc_100to125', sa.Float),
    sa.Column('b_inc_125to150', sa.Float), sa.Column('b_inc_150to200', sa.Float),
    sa.Column('b_inc_200more', sa.Float), sa.Column('w_inc_total', sa.Float),
    sa.Column('w_inc_under10', sa.Float), sa.Column('w_inc_10to15', sa.Float),
    sa.Column('w_inc_15to20', sa.Float), sa.Column('w_inc_20to25', sa.Float),
    sa.Column('w_inc_25to30', sa.Float), sa.Column('w_inc_30to35', sa.Float),
    sa.Column('w_inc_35to40', sa.Float), sa.Column('w_inc_40to45', sa.Float),
    sa.Column('w_inc_45to50', sa.Float), sa.Column('w_inc_50to60', sa.Float),
    sa.Column('w_inc_60to75', sa.Float), sa.Column('w_inc_75to100', sa.Float),
    sa.Column('w_inc_100to125', sa.Float), sa.Column('w_inc_125to150', sa.Float),
    sa.Column('w_inc_150to200', sa.Float), sa.Column('w_inc_200more', sa.Float),
    sa.Column('binc_under10_percent', sa.Float), sa.Column('binc_under20', sa.Float),
    sa.Column('binc_under20_percent', sa.Float), sa.Column('binc_under40', sa.Float),
    sa.Column('binc_under40_percent', sa.Float),
    sa.Column('winc_under10_percent', sa.Float), sa.Column('winc_under20', sa.Float),
    sa.Column('winc_under20_percent', sa.Float), sa.Column('winc_under40', sa.Float),
    sa.Column('winc_under40_percent', sa.Float),
    sa.Column('bwinc_under40_pdiff', sa.Float), sa.Column('bwinc_under20_pdiff', sa.Float),
    sa.Column('ginc_total', sa.Float), sa.Column('male_inc', sa.Float),
    sa.Column('male_inc_alone', sa.Float), sa.Column('female_inc', sa.Float),
    sa.Column('female_inc_alone', sa.Float), sa.Column('total_unemp', sa.Float),
    sa.Column('one_race_unemp', sa.Float), sa.Column('w_unemp', sa.Float),
    sa.Column('b_unemp', sa.Float), sa.Column('male_worked_ft', sa.Float),
    sa.Column('w_male_empdata', sa.Float), sa.Column('w_male_worked_ft', sa.Float),
    sa.Column('w_m_unemp_ft', sa.Float), sa.Column('b_male_empdata', sa.Float),
    sa.Column('b_male_worked_ft', sa.Float), sa.Column('b_m_unemp_ft', sa.Float)
)

metadata.create_all(conn)

