-- Table: mugshots_charges_july2015_grouped

-- DROP TABLE mugshots_charges_july2015_grouped;

CREATE TABLE mugshots_charges_july2015_grouped
(
	charges_arrest_id character varying NOT NULL,
	charge_string_count double precision,
	charge_coded_count double precision,
	any_charge_coded double precision,
	--
	murder double precision,
	rape double precision,
	robbery double precision,
	assault double precision,
	burglary double precision,
	theft double precision,
	auto_theft double precision,
	fraud double precision,
	embez double precision,
	mar_poss double precision,
	coc_poss double precision,
	othdrug_poss double precision,
	mar_sale double precision,
	coc_sale double precision,
	othdrug_sale double precision,
	sex_offense double precision,
	ipv double precision,
	dui double precision,
	drunk_public double precision,
	disorder double precision,
	loiter_prowl double precision,
	driving double precision,
	harass_stalk double precision,
	child_sex_offense double precision,
	weapon double precision,
	speeding double precision,
	reckless_driving double precision,
	no_license double precision,
	resist double precision,
	probation double precision,
	parole double precision,
	arson double precision,
	contempt_fail_appear double precision,
	immigration double precision,
	paraphernalia double precision,
	alcohol double precision,
	gambling double precision,
	felony double precision,
	misdemeanor double precision,
	vandalism double precision,
	prost_minor double precision,
	prost_only double precision,
	prost_traf double precision,
	prost_patron double precision,
	prost_minor_only double precision,
	prost_pimp double precision,
	any_attempted double precision,
	--
	murder_sum double precision,
	rape_sum double precision,
	robbery_sum double precision,
	assault_sum double precision,
	burglary_sum double precision,
	theft_sum double precision,
	auto_theft_sum double precision,
	fraud_sum double precision,
	embez_sum double precision,
	mar_poss_sum double precision,
	coc_poss_sum double precision,
	othdrug_poss_sum double precision,
	mar_sale_sum double precision,
	coc_sale_sum double precision,
	othdrug_sale_sum double precision,
	sex_offense_sum double precision,
	ipv_sum double precision,
	dui_sum double precision,
	drunk_public_sum double precision,
	disorder_sum double precision,
	loiter_prowl_sum double precision,
	driving_sum double precision,
	harass_stalk_sum double precision,
	child_sex_offense_sum double precision,
	weapon_sum double precision,
	speeding_sum double precision,
	reckless_driving_sum double precision,
	no_license_sum double precision,
	resist_sum double precision,
	probation_sum double precision,
	parole_sum double precision,
	arson_sum double precision,
	contempt_fail_appear_sum double precision,
	immigration_sum double precision,
	paraphernalia_sum double precision,
	alcohol_sum double precision,
	gambling_sum double precision,
	felony_sum double precision,
	misdemeanor_sum double precision,
	vandalism_sum double precision,
	prost_minor_sum double precision,
	prost_only_sum double precision,
	prost_traf_sum double precision,
	prost_patron_sum double precision,
	prost_minor_only_sum double precision,
	prost_pimp_sum double precision,
	charge_coded_sum double precision,
	attempted_sum double precision,
  CONSTRAINT mugshots_charges_july2015_grouped_arrest_id_fkey FOREIGN KEY (charges_arrest_id)
      REFERENCES mugshots_july2015 (arrest_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE mugshots_charges_july2015_grouped
  OWNER TO roesler;