-- Table: mugshots2015_male

-- DROP TABLE mugshots2015_male;

CREATE TABLE mugshots2015_male
(
  scraping_arrest_id integer,
  county character varying,
  state character varying,
  county_no character varying,
  name character varying,
  download_date timestamp without time zone,
  all_charges character varying,
  age double precision,
  gender character varying,
  zipcode double precision,
  date character varying,
  birthday character varying,
  race character varying,
  multi double precision,
  am_ind double precision,
  hispanic double precision,
  east_asian double precision,
  asian double precision,
  black double precision,
  white double precision,
  address character varying,
  page_views character varying,
  views_per_day double precision,
  views double precision,
  views_days double precision,
  views_date character varying,
  multi_race_whisp double precision,
  multi_race_nohisp double precision,
  white_only double precision,
  am_ind_only double precision,
  asian_only double precision,
  east_asian_only double precision,
  hispanic_only double precision,
  black_only double precision,
  white_only_ighisp double precision,
  am_ind_only_ighisp double precision,
  asian_only_ighisp double precision,
  east_asian_only_ighisp double precision,
  black_only_ighisp double precision,
  black_not_white double precision,
  racial_minority double precision,
  arrest_id character varying NOT NULL,
  charges_arrest_id character varying NOT NULL,
  charge_string_count double precision,
  charge_coded_count double precision,
  any_charge_coded double precision,
  murder double precision,
  rape double precision,
  robbery double precision,
  assault double precision,
  burglary double precision,
  theft double precision,
  auto_theft double precision,
  fraud double precision,
  embez double precision,
  mar_poss double precision,
  coc_poss double precision,
  othdrug_poss double precision,
  mar_sale double precision,
  coc_sale double precision,
  othdrug_sale double precision,
  sex_offense double precision,
  ipv double precision,
  dui double precision,
  drunk_public double precision,
  disorder double precision,
  loiter_prowl double precision,
  driving double precision,
  harass_stalk double precision,
  child_sex_offense double precision,
  speeding double precision,
  reckless_driving double precision,
  no_license double precision,
  any_attempted double precision,
  murder_sum double precision,
  rape_sum double precision,
  robbery_sum double precision,
  assault_sum double precision,
  burglary_sum double precision,
  theft_sum double precision,
  auto_theft_sum double precision,
  fraud_sum double precision,
  embez_sum double precision,
  mar_poss_sum double precision,
  coc_poss_sum double precision,
  othdrug_poss_sum double precision,
  mar_sale_sum double precision,
  coc_sale_sum double precision,
  othdrug_sale_sum double precision,
  sex_offense_sum double precision,
  ipv_sum double precision,
  dui_sum double precision,
  drunk_public_sum double precision,
  disorder_sum double precision,
  loiter_prowl_sum double precision,
  driving_sum double precision,
  harass_stalk_sum double precision,
  child_sex_offense_sum double precision,
  speeding_sum double precision,
  reckless_driving_sum double precision,
  no_license_sum double precision,
  attempted_sum double precision,
  CONSTRAINT mugshots2015_male_pkey PRIMARY KEY (arrest_id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE mugshots2015_male
  OWNER TO roesler;

-- Index: county_male_idx

-- DROP INDEX county_male_idx;

CREATE INDEX county_male_idx
  ON mugshots2015_male
  USING btree
  (county_no COLLATE pg_catalog."default");