-- Table: nibrs_offenders_13m_lemas_zip

-- DROP TABLE nibrs_offenders_13m_lemas_zip;

CREATE TABLE nibrs_offenders_13m_lemas_zip
(
  recsarr double precision,
  pop_group double precision,
  record_type double precision,
  arrest_transaction3 character varying,
  recsofs double precision,
  recsofr double precision,
  arrest_transaction2 character varying,
  state_no double precision,
  ucr_arrest_offense_code1 double precision,
  fips_county1 double precision,
  arrest_type2 double precision,
  arrest_type3 double precision,
  arrest_type1 double precision,
  arrestee_gender3 character varying,
  recsvic double precision,
  ucr_arrest_offense_code2 double precision,
  core_city double precision,
  arrest_seqno3 double precision,
  arrest_seqno2 double precision,
  arrest_seqno1 double precision,
  offender_seqno1 double precision,
  months_reported double precision,
  offender_seqno2 double precision,
  arrest_transaction1 character varying,
  ucr_county4 double precision,
  ucr_county5 double precision,
  ucr_county2 double precision,
  ucr_county3 double precision,
  ucr_county1 double precision,
  recsprp double precision,
  arrestee_race2 character varying,
  race character varying,
  arrestee_ethnicity2 character varying,
  arrestee_ethnicity3 character varying,
  gender character varying,
  arrestee_race1 character varying,
  agency_indicator double precision,
  arrestee_resident_status1 double precision,
  ethnicity character varying,
  offense_segments double precision,
  offender_seqno double precision,
  allofns character varying,
  transaction_number character varying,
  fips_county3 double precision,
  fips_county2 double precision,
  state character varying,
  covered_ori character varying,
  fips_county5 double precision,
  fips_county4 double precision,
  recsadm double precision,
  country_division double precision,
  arrestee_disposition_u18_1 double precision,
  arrestee_disposition_u18_3 double precision,
  arrestee_disposition_u18_2 double precision,
  incident character varying,
  offender_seqno3 double precision,
  ori character varying,
  city_name character varying,
  arrestee_gender1 character varying,
  ucr_arrest_offense_code3 double precision,
  arrestee_gender2 character varying,
  arrestee_race3 character varying,
  ucr_offense_code1 double precision,
  region double precision,
  ucr_offense_code3 double precision,
  arrestee_resident_status2 double precision,
  arrestee_resident_status3 double precision,
  ucr_offense_code2 double precision,
  arrest_seqno double precision,
  arrestee_ethnicity1 character varying,
  multiple_arrests1 double precision,
  multiple_arrests2 double precision,
  multiple_arrests3 double precision,
  attempted2 double precision,
  attempted3 double precision,
  attempted1 double precision,
  fips_county1_digits double precision,
  fips_county1_no double precision,
  fips_county2_digits double precision,
  fips_county2_no double precision,
  fips_county3_digits double precision,
  fips_county3_no double precision,
  fips_county4_digits double precision,
  fips_county4_no double precision,
  fips_county5_digits double precision,
  fips_county5_no double precision,
  incident_date character varying,
  arrest_date character varying,
  arrest_date1 character varying,
  arrest_date2 character varying,
  arrest_date3 character varying,
  age double precision,
  arrestee_age1 double precision,
  arrestee_age2 double precision,
  arrestee_age3 double precision,
  number_records double precision,
  internal_offender_id double precision NOT NULL,
  arrest_arson integer DEFAULT 0,
  arrest_aggravated_assault integer DEFAULT 0,
  arrest_simple_assault integer DEFAULT 0,
  arrest_intimidation integer DEFAULT 0,
  arrest_bribery integer DEFAULT 0,
  arrest_burglary integer DEFAULT 0,
  arrest_forgery integer DEFAULT 0,
  arrest_vandalism integer DEFAULT 0,
  arrest_drugs_narcotics integer DEFAULT 0,
  arrest_drug_equipment integer DEFAULT 0,
  arrest_embezzlement integer DEFAULT 0,
  arrest_extortion integer DEFAULT 0,
  arrest_false_pretenses integer DEFAULT 0,
  arrest_credit_card integer DEFAULT 0,
  arrest_impersonation integer DEFAULT 0,
  arrest_welfare_fraud integer DEFAULT 0,
  arrest_wire_fraud integer DEFAULT 0,
  arrest_betting integer DEFAULT 0,
  arrest_operating_gambling integer DEFAULT 0,
  arrest_gambling_equipment integer DEFAULT 0,
  arrest_sports_tampering integer DEFAULT 0,
  arrest_murder integer DEFAULT 0,
  arrest_negligent_manslaughter integer DEFAULT 0,
  arrest_justifiable_homicide integer DEFAULT 0,
  arrest_sex_trafficking integer DEFAULT 0,
  arrest_labor_trafficking integer DEFAULT 0,
  arrest_kidnapping integer DEFAULT 0,
  arrest_pocket_picking integer DEFAULT 0,
  arrest_purse_snatching integer DEFAULT 0,
  arrest_shoplifting integer DEFAULT 0,
  arrest_building_theft integer DEFAULT 0,
  arrest_theft_from_machine integer DEFAULT 0,
  arrest_theft_from_auto integer DEFAULT 0,
  arrest_auto_parts_theft integer DEFAULT 0,
  arrest_other_theft integer DEFAULT 0,
  arrest_auto_theft integer DEFAULT 0,
  arrest_pornography integer DEFAULT 0,
  arrest_prostitution integer DEFAULT 0,
  arrest_prostitution_promotion integer DEFAULT 0,
  arrest_prostitution_purchase integer DEFAULT 0,
  arrest_robbery integer DEFAULT 0,
  arrest_forcible_rape integer DEFAULT 0,
  arrest_forcible_sodomy integer DEFAULT 0,
  arrest_rape_object integer DEFAULT 0,
  arrest_forcible_fondling integer DEFAULT 0,
  arrest_incest integer DEFAULT 0,
  arrest_statutory_rape integer DEFAULT 0,
  arrest_stolen_property integer DEFAULT 0,
  arrest_weapon integer DEFAULT 0,
  arrest_assault_general integer DEFAULT 0,
  arrest_drugs_general integer DEFAULT 0,
  arrest_fraud_general integer DEFAULT 0,
  arrest_gambling_general integer DEFAULT 0,
  arrest_homicide_general integer DEFAULT 0,
  arrest_trafficking_general integer DEFAULT 0,
  arrest_theft_general integer DEFAULT 0,
  arrest_prostitution_general integer DEFAULT 0,
  arrest_sex_offense_forcible integer DEFAULT 0,
  arrest_sex_offense_nonforcible integer DEFAULT 0,
  arrest_bad_check integer DEFAULT 0,
  arrest_loitering integer DEFAULT 0,
  arrest_disorder integer DEFAULT 0,
  arrest_dui integer DEFAULT 0,
  arrest_drunk integer DEFAULT 0,
  arrest_family_nonv integer DEFAULT 0,
  arrest_liquor_law integer DEFAULT 0,
  arrest_peeping_tom integer DEFAULT 0,
  arrest_runaway integer DEFAULT 0,
  arrest_trespass integer DEFAULT 0,
  arrest_other_offense integer DEFAULT 0,
  arrest_ucr_offense_code_unknown integer DEFAULT 0,
  offense_arson integer DEFAULT 0,
  offense_aggravated_assault integer DEFAULT 0,
  offense_simple_assault integer DEFAULT 0,
  offense_intimidation integer DEFAULT 0,
  offense_bribery integer DEFAULT 0,
  offense_burglary integer DEFAULT 0,
  offense_forgery integer DEFAULT 0,
  offense_vandalism integer DEFAULT 0,
  offense_drugs_narcotics integer DEFAULT 0,
  offense_drug_equipment integer DEFAULT 0,
  offense_embezzlement integer DEFAULT 0,
  offense_extortion integer DEFAULT 0,
  offense_false_pretenses integer DEFAULT 0,
  offense_credit_card integer DEFAULT 0,
  offense_impersonation integer DEFAULT 0,
  offense_welfare_fraud integer DEFAULT 0,
  offense_wire_fraud integer DEFAULT 0,
  offense_betting integer DEFAULT 0,
  offense_operating_gambling integer DEFAULT 0,
  offense_gambling_equipment integer DEFAULT 0,
  offense_sports_tampering integer DEFAULT 0,
  offense_murder integer DEFAULT 0,
  offense_negligent_manslaughter integer DEFAULT 0,
  offense_justifiable_homicide integer DEFAULT 0,
  offense_sex_trafficking integer DEFAULT 0,
  offense_labor_trafficking integer DEFAULT 0,
  offense_kidnapping integer DEFAULT 0,
  offense_pocket_picking integer DEFAULT 0,
  offense_purse_snatching integer DEFAULT 0,
  offense_shoplifting integer DEFAULT 0,
  offense_building_theft integer DEFAULT 0,
  offense_theft_from_machine integer DEFAULT 0,
  offense_theft_from_auto integer DEFAULT 0,
  offense_auto_parts_theft integer DEFAULT 0,
  offense_other_theft integer DEFAULT 0,
  offense_auto_theft integer DEFAULT 0,
  offense_pornography integer DEFAULT 0,
  offense_prostitution integer DEFAULT 0,
  offense_prostitution_promotion integer DEFAULT 0,
  offense_prostitution_purchase integer DEFAULT 0,
  offense_robbery integer DEFAULT 0,
  offense_forcible_rape integer DEFAULT 0,
  offense_forcible_sodomy integer DEFAULT 0,
  offense_rape_object integer DEFAULT 0,
  offense_forcible_fondling integer DEFAULT 0,
  offense_incest integer DEFAULT 0,
  offense_statutory_rape integer DEFAULT 0,
  offense_stolen_property integer DEFAULT 0,
  offense_weapon integer DEFAULT 0,
  offense_assault_general integer DEFAULT 0,
  offense_drugs_general integer DEFAULT 0,
  offense_fraud_general integer DEFAULT 0,
  offense_gambling_general integer DEFAULT 0,
  offense_homicide_general integer DEFAULT 0,
  offense_trafficking_general integer DEFAULT 0,
  offense_theft_general integer DEFAULT 0,
  offense_prostitution_general integer DEFAULT 0,
  offense_sex_offense_forcible integer DEFAULT 0,
  offense_sex_offense_nonforcible integer DEFAULT 0,
  offense_ucr_offense_code_unknown integer DEFAULT 0,
  cw_ori character varying,
  zipcode double precision,
  ori7 character varying,
  ori9 character varying,
  agencyid character varying,
  lemas_type character varying,
  tribalpd character varying,
  countypd character varying,
  bjs_agencyname character varying,
  city character varying,
  statename character varying,
  statecode character varying,
  lemas_zipcode character varying,
  sampletype_final character varying,
  stratcode character varying,
  pers_pdsw_mft double precision,
  pers_pdsw_mpt double precision,
  pers_pdsw_fft double precision,
  pers_pdsw_fpt double precision,
  pers_fts_wht double precision,
  pers_fts_blk double precision,
  pers_fts_hsp double precision,
  pers_fts_ind double precision,
  pers_fts_asn double precision,
  pers_fts_haw double precision,
  pers_fts_two double precision,
  pers_fts_unk double precision,
  pers_fts_racetot double precision,
  pay_sal_exc_min double precision,
  pay_sal_exc_max double precision,
  pay_sal_sgt_min double precision,
  pay_sal_sgt_max double precision,
  pay_sal_ofcr_min double precision,
  pay_sal_ofcr_max double precision,
  pay_inct_edu double precision,
  pay_inct_voc double precision,
  pay_inct_lang double precision,
  pay_inct_spcl double precision,
  pay_inct_hzrd double precision,
  pay_inct_sd double precision,
  pay_inct_rinc double precision,
  pay_inct_mrt double precision,
  hir_trn_no_l double precision,
  hir_trn_no_p double precision,
  hir_trn_crs_l double precision,
  hir_trn_crs_p double precision,
  hir_trn_fld_l double precision,
  hir_trn_fld_p double precision,
  hir_edu_no double precision,
  hir_edu_hs double precision,
  hir_edu_scol double precision,
  hir_edu_ad double precision,
  hir_edu_bd double precision,
  hir_mil double precision,
  hir_bd_var double precision,
  bdgt_mnth character varying,
  bdgt_ttl double precision,
  bdgt_ttl_est double precision,
  bdgt_src_mnc double precision,
  bdgt_src_cnty double precision,
  bdgt_src_state double precision,
  bdgt_src_fed double precision,
  bdgt_src_cont double precision,
  bdgt_src_asst double precision,
  bdgt_src_fee double precision,
  bdgt_src_othr double precision,
  bdgt_src_spec character varying,
  com_mis double precision,
  com_trn_rec character varying,
  com_trn_insrv character varying,
  com_sara double precision,
  com_nsara double precision,
  com_col double precision,
  com_ptnr double precision,
  com_bt double precision,
  com_nbt double precision,
  com_surv double precision,
  tech_typ_gun double precision,
  tech_typ_lic double precision,
  tech_typ_vpub double precision,
  tech_typ_vveh double precision,
  tech_typ_vpat double precision,
  tech_typ_vwpn double precision,
  tech_typ_vothr double precision,
  tech_eac_mrec double precision,
  tech_eac_drec double precision,
  tech_eac_crim double precision,
  tech_eac_warr double precision,
  tech_eac_prot double precision,
  tech_eac_adrs double precision,
  tech_crs double precision,
  tech_cred_sum double precision,
  tech_cred_nar double precision,
  tech_rec_sus double precision,
  tech_who_no double precision,
  tech_who_staff double precision,
  tech_who_extr double precision,
  tech_many_fts double precision,
  tech_many_ftns double precision,
  tech_out_law double precision,
  tech_out_gov double precision,
  tech_out_univ double precision,
  tech_out_vend double precision,
  tech_out_othr double precision,
  tech_web_none double precision,
  tech_web_jur double precision,
  tech_publ_file double precision,
  tech_media_tw double precision,
  tech_media_fb double precision,
  tech_media_ytbe double precision,
  safe_finc character varying,
  no_record_force double precision,
  safe_frc_inc double precision,
  safe_frc_offc double precision,
  safe_fttl double precision,
  safe_fttl_est double precision,
  safe_fttl_unk double precision,
  safe_sepr double precision,
  safe_sepr_est double precision,
  safe_sepr_unk double precision,
  basewt double precision,
  nradjust double precision,
  finalwt double precision,
  ftsworn double precision,
  ptsworn double precision,
  ftciv double precision,
  ptciv double precision,
  safe_finc_binary double precision,
  CONSTRAINT nibrs_offenders_13m_lemas_zip_pkey PRIMARY KEY (internal_offender_id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE nibrs_offenders_13m_lemas_zip
  OWNER TO roesler;