-- Table: nibrs_arrests_13m_lemas_zip

-- DROP TABLE nibrs_arrests_13m_lemas_zip;

CREATE TABLE nibrs_arrests_13m_lemas_zip
(
  agency_indicator double precision,
  recsarr double precision,
  resident_status double precision,
  pop_group double precision,
  record_type character varying,
  ucr_offense_code double precision,
  disposition_u18 double precision,
  multiple_arrests double precision,
  recsofs double precision,
  recsofr double precision,
  state_no double precision,
  state character varying,
  fips_county3 double precision,
  fips_county2 double precision,
  fips_county1 double precision,
  covered_ori character varying,
  ethnicity character varying,
  fips_county5 double precision,
  fips_county4 double precision,
  recsadm double precision,
  arrest_seqno double precision,
  recsvic double precision,
  core_city double precision,
  country_division double precision,
  months_reported double precision,
  arrest_type double precision,
  incident character varying,
  ori character varying,
  city_name character varying,
  ucr_county4 double precision,
  ucr_county5 double precision,
  ucr_county2 double precision,
  ucr_county3 double precision,
  ucr_county1 double precision,
  recsprp double precision,
  gender character varying,
  region double precision,
  ucr_offense_code3 double precision,
  transaction_number character varying,
  race character varying,
  ucr_offense_code1 double precision,
  attempted2 double precision,
  attempted3 double precision,
  attempted1 double precision,
  ucr_offense_code2 double precision,
  fips_county1_digits double precision,
  fips_county1_no double precision,
  fips_county2_digits double precision,
  fips_county2_no double precision,
  fips_county3_digits double precision,
  fips_county3_no double precision,
  fips_county4_digits double precision,
  fips_county4_no double precision,
  fips_county5_digits double precision,
  fips_county5_no double precision,
  incident_date character varying,
  arrest_date character varying,
  age double precision,
  number_records double precision,
  internal_offender_id double precision NOT NULL,
  arson integer DEFAULT 0,
  aggravated_assault integer DEFAULT 0,
  simple_assault integer DEFAULT 0,
  intimidation integer DEFAULT 0,
  bribery integer DEFAULT 0,
  burglary integer DEFAULT 0,
  forgery integer DEFAULT 0,
  vandalism integer DEFAULT 0,
  drugs_narcotics integer DEFAULT 0,
  drug_equipment integer DEFAULT 0,
  embezzlement integer DEFAULT 0,
  extortion integer DEFAULT 0,
  false_pretenses integer DEFAULT 0,
  credit_card integer DEFAULT 0,
  impersonation integer DEFAULT 0,
  welfare_fraud integer DEFAULT 0,
  wire_fraud integer DEFAULT 0,
  betting integer DEFAULT 0,
  operating_gambling integer DEFAULT 0,
  gambling_equipment integer DEFAULT 0,
  sports_tampering integer DEFAULT 0,
  murder integer DEFAULT 0,
  negligent_manslaughter integer DEFAULT 0,
  justifiable_homicide integer DEFAULT 0,
  sex_trafficking integer DEFAULT 0,
  labor_trafficking integer DEFAULT 0,
  kidnapping integer DEFAULT 0,
  pocket_picking integer DEFAULT 0,
  purse_snatching integer DEFAULT 0,
  shoplifting integer DEFAULT 0,
  building_theft integer DEFAULT 0,
  theft_from_machine integer DEFAULT 0,
  theft_from_auto integer DEFAULT 0,
  auto_parts_theft integer DEFAULT 0,
  other_theft integer DEFAULT 0,
  auto_theft integer DEFAULT 0,
  pornography integer DEFAULT 0,
  prostitution integer DEFAULT 0,
  prostitution_promotion integer DEFAULT 0,
  prostitution_purchase integer DEFAULT 0,
  robbery integer DEFAULT 0,
  forcible_rape integer DEFAULT 0,
  forcible_sodomy integer DEFAULT 0,
  rape_object integer DEFAULT 0,
  forcible_fondling integer DEFAULT 0,
  incest integer DEFAULT 0,
  statutory_rape integer DEFAULT 0,
  stolen_property integer DEFAULT 0,
  weapon integer DEFAULT 0,
  assault_general integer DEFAULT 0,
  drugs_general integer DEFAULT 0,
  fraud_general integer DEFAULT 0,
  gambling_general integer DEFAULT 0,
  homicide_general integer DEFAULT 0,
  trafficking_general integer DEFAULT 0,
  theft_general integer DEFAULT 0,
  prostitution_general integer DEFAULT 0,
  sex_offense_forcible integer DEFAULT 0,
  sex_offense_nonforcible integer DEFAULT 0,
  bad_check integer DEFAULT 0,
  loitering integer DEFAULT 0,
  disorder integer DEFAULT 0,
  dui integer DEFAULT 0,
  drunk integer DEFAULT 0,
  family_nonv integer DEFAULT 0,
  liquor_law integer DEFAULT 0,
  peeping_tom integer DEFAULT 0,
  runaway integer DEFAULT 0,
  trespass integer DEFAULT 0,
  other_offense integer DEFAULT 0,
  ucr_offense_code_unknown integer DEFAULT 0,
  ori9 character varying,
  zipcode double precision,
  lemas_ori7 character varying,
  lemas_ori9 character varying,
  agencyid character varying,
  lemas_type character varying,
  tribalpd character varying,
  countypd character varying,
  bjs_agencyname character varying,
  city character varying,
  statename character varying,
  statecode character varying,
  lemas_zipcode character varying,
  sampletype_final character varying,
  stratcode character varying,
  pers_pdsw_mft double precision,
  pers_pdsw_mpt double precision,
  pers_pdsw_fft double precision,
  pers_pdsw_fpt double precision,
  pers_fts_wht double precision,
  pers_fts_blk double precision,
  pers_fts_hsp double precision,
  pers_fts_ind double precision,
  pers_fts_asn double precision,
  pers_fts_haw double precision,
  pers_fts_two double precision,
  pers_fts_unk double precision,
  pers_fts_racetot double precision,
  pay_sal_exc_min double precision,
  pay_sal_exc_max double precision,
  pay_sal_sgt_min double precision,
  pay_sal_sgt_max double precision,
  pay_sal_ofcr_min double precision,
  pay_sal_ofcr_max double precision,
  pay_inct_edu double precision,
  pay_inct_voc double precision,
  pay_inct_lang double precision,
  pay_inct_spcl double precision,
  pay_inct_hzrd double precision,
  pay_inct_sd double precision,
  pay_inct_rinc double precision,
  pay_inct_mrt double precision,
  hir_trn_no_l double precision,
  hir_trn_no_p double precision,
  hir_trn_crs_l double precision,
  hir_trn_crs_p double precision,
  hir_trn_fld_l double precision,
  hir_trn_fld_p double precision,
  hir_edu_no double precision,
  hir_edu_hs double precision,
  hir_edu_scol double precision,
  hir_edu_ad double precision,
  hir_edu_bd double precision,
  hir_mil double precision,
  hir_bd_var double precision,
  bdgt_mnth character varying,
  bdgt_ttl double precision,
  bdgt_ttl_est double precision,
  bdgt_src_mnc double precision,
  bdgt_src_cnty double precision,
  bdgt_src_state double precision,
  bdgt_src_fed double precision,
  bdgt_src_cont double precision,
  bdgt_src_asst double precision,
  bdgt_src_fee double precision,
  bdgt_src_othr double precision,
  bdgt_src_spec character varying,
  com_mis double precision,
  com_trn_rec character varying,
  com_trn_insrv character varying,
  com_sara double precision,
  com_nsara double precision,
  com_col double precision,
  com_ptnr double precision,
  com_bt double precision,
  com_nbt double precision,
  com_surv double precision,
  tech_typ_gun double precision,
  tech_typ_lic double precision,
  tech_typ_vpub double precision,
  tech_typ_vveh double precision,
  tech_typ_vpat double precision,
  tech_typ_vwpn double precision,
  tech_typ_vothr double precision,
  tech_eac_mrec double precision,
  tech_eac_drec double precision,
  tech_eac_crim double precision,
  tech_eac_warr double precision,
  tech_eac_prot double precision,
  tech_eac_adrs double precision,
  tech_crs double precision,
  tech_cred_sum double precision,
  tech_cred_nar double precision,
  tech_rec_sus double precision,
  tech_who_no double precision,
  tech_who_staff double precision,
  tech_who_extr double precision,
  tech_many_fts double precision,
  tech_many_ftns double precision,
  tech_out_law double precision,
  tech_out_gov double precision,
  tech_out_univ double precision,
  tech_out_vend double precision,
  tech_out_othr double precision,
  tech_web_none double precision,
  tech_web_jur double precision,
  tech_publ_file double precision,
  tech_media_tw double precision,
  tech_media_fb double precision,
  tech_media_ytbe double precision,
  safe_finc character varying,
  no_record_force double precision,
  safe_frc_inc double precision,
  safe_frc_offc double precision,
  safe_fttl double precision,
  safe_fttl_est double precision,
  safe_fttl_unk double precision,
  safe_sepr double precision,
  safe_sepr_est double precision,
  safe_sepr_unk double precision,
  basewt double precision,
  nradjust double precision,
  finalwt double precision,
  ftsworn double precision,
  ptsworn double precision,
  ftciv double precision,
  ptciv double precision,
  safe_finc_binary double precision,
  CONSTRAINT nibrs_arrests_13m_lemas_zip_pkey PRIMARY KEY (internal_offender_id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE nibrs_arrests_13m_lemas_zip
  OWNER TO roesler;

-- Index: nibrs_arrests_13m_lemas_zip_idx

-- DROP INDEX nibrs_arrests_13m_lemas_zip_idx;

CREATE INDEX nibrs_arrests_13m_lemas_zip_idx
  ON nibrs_arrests_13m_lemas_zip
  USING btree
  (ori COLLATE pg_catalog."default");