vars07 = ['zipcode', 'population', 'csllea04_id', 'swnauthemp', 'swnftemp', 'swnptemp', 
    'civftemp', 'civptemp', 'ftgangoff', 'ptgangoff', 'ftdrugoff', 'ptdrugoff', 'numpatr',
    'numinvst', 'white', 'black', 'hispanic', 'asian', 'nathaw', 'amerind', 'multrace',
    'unkrace', 'male', 'female', 'totgender', 'opbudget', 'opbudgest', 'drugforf', 
    'gambforf', 'othrforf', 'asforest', 'totacad', 'totfield', 'totinsrv', 'chiefmin', 'chiefmax',
    'sgtmin', 'sgtmax', 'entrymin', 'entrymax', 'nummrkcars', 'numumkcars', 'numcarcam', 'numuofsust',
    'numuofoth', 'numuofpend', 'numuoftot', 'impbudget', 'impcarcam', 'impgender', 'imprace', 'educpay',
    'cptrnnew', 'cptrninserv', 'cpmission', 'cpacademy', 'cpplan', 'cppartner', 'cpsurvey', 'cpunit', 'cpnone', 'writaptest',
    'voicestress', 'anprobsolv', 'cultdiv', 'confmgt', 'psycheval', 'polyexam', 'perstest', 'intervw', 'drivhis', 'mineduc',
    'edreqexm', 'backgrnd', 'credhis', 'crimhis', 'seclang', 'volhis', 'drugtest', 'medexam', 'phystest',
    'hazardpay', 'meritpay', 'shiftpay', 'skillpay', 'langpay', 'tuitionpay', 'milpay', 'collbarg', 'respay',
    'ccrb', 'ccrbpowers', 'outsideinv', 'agcytype', 'agency', 'ori', 'state', 'city', 'earlywarn',
    'deadforcplcy', 'lessthanplcy', 'codecondplcy', 'offdemplplcy', 'maxhoursplcy',
    'offdcondplcy', 'mediaplcy', 'eapplcy', 'mentillplcy', 'homelessplcy',
    'domdispplcy', 'juvenileplcy', 'limitengplcy', 'incusdthplcy', 'racialprplcy', 'citcompplcy', 'immstatplcy']

vars13 = ['ori7', 'ori9', 'agencyid', 'type', 'tribalpd', 'countypd',
          'bjs_agencyname', 'city', 'statename', 'statecode',
          'zipcode', 'sampletype_final', 'stratcode',
          'pers_pdsw_mft', 'pers_pdsw_mpt', 'pers_pdsw_fft', 'pers_pdsw_fpt',
          'pers_fts_wht', 'pers_fts_blk', 'pers_fts_hsp', 'pers_fts_ind', 'pers_fts_asn',
          'pers_fts_haw', 'pers_fts_two', 'pers_fts_unk', 'pers_fts_racetot',
          'pay_sal_exc_min', 'pay_sal_exc_max', 'pay_sal_sgt_min', 'pay_sal_sgt_max',
          'pay_sal_ofcr_min', 'pay_sal_ofcr_max', 'pay_inct_edu', 'pay_inct_voc',
          'pay_inct_lang', 'pay_inct_spcl', 'pay_inct_hzrd', 'pay_inct_sd', 'pay_inct_rinc',
          'pay_inct_mrt',
          'hir_trn_no_l', 'hir_trn_no_p', 'hir_trn_crs_l', 'hir_trn_crs_p',
          'hir_trn_fld_l', 'hir_trn_fld_p', 'hir_edu_no', 'hir_edu_hs', 'hir_edu_scol',
          'hir_edu_ad', 'hir_edu_bd', 'hir_mil',
          'hir_bd_var', 'bdgt_mnth', 'bdgt_ttl', 'bdgt_ttl_est', 'bdgt_src_mnc',
          'bdgt_src_cnty', 'bdgt_src_state', 'bdgt_src_fed', 'bdgt_src_cont',
          'bdgt_src_asst', 'bdgt_src_fee', 'bdgt_src_othr', 'bdgt_src_spec',
          'com_mis', 'com_trn_rec', 'com_trn_insrv', 'com_sara', 'com_nsara',
          'com_col', 'com_ptnr', 'com_bt', 'com_nbt', 'com_surv',
          'tech_typ_gun', 'tech_typ_lic', 'tech_typ_vpub', 'tech_typ_vveh',
          'tech_typ_vpat', 'tech_typ_vwpn', 'tech_typ_vothr',
          'tech_eac_mrec', 'tech_eac_drec', 'tech_eac_crim', 'tech_eac_warr',
          'tech_eac_prot', 'tech_eac_adrs',
          'tech_crs', 'tech_crec_sum', 'tech_crec_nar', 'tech_rec_sus',
          'tech_who_no', 'tech_who_staff', 'tech_who_extr', 
          'tech_many_fts', 'tech_many_ftns', 'tech_out_law',
          'tech_out_gov', 'tech_out_univ', 'tech_out_vend', 'tech_out_othr',
          'tech_web_none', 'tech_web_jur',
          'tech_publ_file', 'tech_media_tw', 'tech_media_fb', 'tech_media_ytbe',
          'safe_finc', 'no_record_force', 'safe_frc_inc', 'safe_frc_offc',
          'safe_fttl', 'safe_fttl_est', 'safe_fttl_unk',
          'safe_sepr', 'safe_sepr_est', 'safe_sepr_unk',
          'basewt', 'nradjust', 'finalwt', 'ftsworn', 'ptsworn', 'ftciv', 'ptciv', 'pop2012']