-- fix nibrs_arrests_13m_la_off charge coding

UPDATE nibrs_arrests_13m_la_off SET bad_check = 1 WHERE nibrs_arrests_13m_la_off.ucr_offense_code = 901 or nibrs_arrests_13m_la_off.ucr_offense_code1 = 901 or nibrs_arrests_13m_la_off.ucr_offense_code2 = 901 or nibrs_arrests_13m_la_off.ucr_offense_code3 = 901;
UPDATE nibrs_arrests_13m_la_off SET loitering = 1 WHERE nibrs_arrests_13m_la_off.ucr_offense_code = 902 or nibrs_arrests_13m_la_off.ucr_offense_code1 = 902 or nibrs_arrests_13m_la_off.ucr_offense_code2 = 902 or nibrs_arrests_13m_la_off.ucr_offense_code3 = 902;
UPDATE nibrs_arrests_13m_la_off SET disorder = 1 WHERE nibrs_arrests_13m_la_off.ucr_offense_code = 903 or nibrs_arrests_13m_la_off.ucr_offense_code1 = 903 or nibrs_arrests_13m_la_off.ucr_offense_code2 = 903 or nibrs_arrests_13m_la_off.ucr_offense_code3 = 903;
UPDATE nibrs_arrests_13m_la_off SET dui = 1 WHERE nibrs_arrests_13m_la_off.ucr_offense_code = 904 or nibrs_arrests_13m_la_off.ucr_offense_code1 = 904 or nibrs_arrests_13m_la_off.ucr_offense_code2 = 904 or nibrs_arrests_13m_la_off.ucr_offense_code3 = 904;
UPDATE nibrs_arrests_13m_la_off SET drunk = 1 WHERE nibrs_arrests_13m_la_off.ucr_offense_code = 905 or nibrs_arrests_13m_la_off.ucr_offense_code1 = 905 or nibrs_arrests_13m_la_off.ucr_offense_code2 = 905 or nibrs_arrests_13m_la_off.ucr_offense_code3 = 905;
UPDATE nibrs_arrests_13m_la_off SET family_nonv = 1 WHERE nibrs_arrests_13m_la_off.ucr_offense_code = 906 or nibrs_arrests_13m_la_off.ucr_offense_code1 = 906 or nibrs_arrests_13m_la_off.ucr_offense_code2 = 906 or nibrs_arrests_13m_la_off.ucr_offense_code3 = 906;
UPDATE nibrs_arrests_13m_la_off SET liquor_law = 1 WHERE nibrs_arrests_13m_la_off.ucr_offense_code = 907 or nibrs_arrests_13m_la_off.ucr_offense_code1 = 907 or nibrs_arrests_13m_la_off.ucr_offense_code2 = 907 or nibrs_arrests_13m_la_off.ucr_offense_code3 = 907;
UPDATE nibrs_arrests_13m_la_off SET peeping_tom = 1 WHERE nibrs_arrests_13m_la_off.ucr_offense_code = 908 or nibrs_arrests_13m_la_off.ucr_offense_code1 = 908 or nibrs_arrests_13m_la_off.ucr_offense_code2 = 908 or nibrs_arrests_13m_la_off.ucr_offense_code3 = 908;
UPDATE nibrs_arrests_13m_la_off SET runaway = 1 WHERE nibrs_arrests_13m_la_off.ucr_offense_code = 909 or nibrs_arrests_13m_la_off.ucr_offense_code1 = 909 or nibrs_arrests_13m_la_off.ucr_offense_code2 = 909 or nibrs_arrests_13m_la_off.ucr_offense_code3 = 909;
UPDATE nibrs_arrests_13m_la_off SET trespass = 1 WHERE nibrs_arrests_13m_la_off.ucr_offense_code = 910 or nibrs_arrests_13m_la_off.ucr_offense_code1 = 910 or nibrs_arrests_13m_la_off.ucr_offense_code2 = 910 or nibrs_arrests_13m_la_off.ucr_offense_code3 = 910;
UPDATE nibrs_arrests_13m_la_off SET other_offense = 1 WHERE nibrs_arrests_13m_la_off.ucr_offense_code = 990 or nibrs_arrests_13m_la_off.ucr_offense_code1 = 990 or nibrs_arrests_13m_la_off.ucr_offense_code2 = 990 or nibrs_arrests_13m_la_off.ucr_offense_code3 = 990;