---
title: "Crime Data Plots"
output: html_document
---

```{r}
rm(list = ls())
library(rms)
library(ggplot2)
library(plyr)
library(reshape)
library("RColorBrewer")

load("~/Dropbox/Projects/Mugshots Project/Code/analysis/basic.RData")
```

Barplot of black and white offenders' arrest rates

```{r, echo=FALSE}
  offenders_arrested <- tapply(dataset$arrested, dataset$black_not_white, FUN = mean, na.rm=TRUE) * 100
  simple_assault_arrested <- tapply(simple_assault_data$arrested, simple_assault_data$black_not_white, FUN = mean, na.rm=TRUE) * 100
  aggravated_assault_arrested <- tapply(aggravated_assault_data$arrested, aggravated_assault_data$black_not_white, FUN = mean, na.rm=TRUE) * 100
  intimidation_arrested <- tapply(intimidation_data$arrested, intimidation_data$black_not_white, FUN = mean, na.rm=TRUE) * 100
  robbery_arrested <- tapply(robbery_data$arrested, robbery_data$black_not_white, FUN = mean, na.rm=TRUE) * 100
  shoplifting_arrested <- tapply(shoplifting_data$arrested, shoplifting_data$black_not_white, FUN = mean, na.rm=TRUE) * 100
  vandalism_arrested <- tapply(vandalism_data$arrested, vandalism_data$black_not_white, FUN = mean, na.rm=TRUE) * 100
  drugs_narcotics_arrested <- tapply(drugs_narcotics_data$arrested, drugs_narcotics_data$black_not_white, FUN = mean, na.rm=TRUE) * 100
  drug_equipment_arrested <- tapply(drug_equipment_data$arrested, drug_equipment_data$black_not_white, FUN = mean, na.rm=TRUE) * 100
  
  TAB <- rbind(offenders_arrested, simple_assault_arrested, aggravated_assault_arrested, intimidation_arrested, robbery_arrested, shoplifting_arrested, vandalism_arrested, drugs_narcotics_arrested, drug_equipment_arrested)
  
  df <- data.frame(TAB)
  df <- rename(df, c("X0" = "White", "X1" = "Black"))
  df <- t(df)
  
  Names <- names(df)
  df.m <- melt(df, id.vars = Names)
  
  df.m$X2 <- factor(df.m$X2, levels = c("offenders_arrested", "simple_assault_arrested", "aggravated_assault_arrested", "intimidation_arrested", "robbery_arrested", "shoplifting_arrested", "vandalism_arrested", "drugs_narcotics_arrested", "drug_equipment_arrested"), labels = c("All", "Simple Assault", "Aggravated Assault", "Intimidation", "Robbery","Shoplifting", "Vandalism", "Drugs / Narcotics", "Drug Equipment"))
  
  table_X2 <- table(df.m$X2)
  x_levels <- names(table_X2)[order(table_X2)]
  df.m$X2 <- factor(df.m$X2, levels = x_levels)
  df.m$X1 <- factor(df.m$X1, levels = c('White', 'Black'))
  
  ggplot(df.m, aes(X2, value)) +   
    geom_bar(aes(fill = X1), position = "dodge", stat="identity") +
    ylab("Percent Arrested") + xlab("Offense") +
    ggtitle("Percent Black and White Offenders Arrested") + theme_bw() +
    labs(fill = "Offender Race") + ylim(0, 100) +
    theme(axis.text.x = element_text(size = 10, angle = 45, vjust = 0.5)) +
    geom_text(data = df.m[df.m$X1 == 'White',],
              aes(label = round(value, 0), hjust = 1.9, vjust = -0.5), size = 4) +
    geom_text(data = df.m[df.m$X1 == 'Black',],
              aes(label = round(value, 0), hjust = -0.7, vjust = -0.5), size = 4)
```

